name: rush_time_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_mobile_ads: ^2.4.0
  # or admob_flutter: ^3.0.0, not both
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  #firebase_core: ^2.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_mobile_ads: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png # アセットとしてのアイコンを追加

flutter_launcher_icons:
  image_path: "assets/images/icon.png" # このアイコンをアプリのランチャーアイコンとして使用
  android: true
  ios: true
